version: '3.8'

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/crm.eleviq.buzz.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - backend_uploads:/usr/src/app/uploads:ro

  backend:
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_BUSINESS_CLIENT_ID=${GOOGLE_BUSINESS_CLIENT_ID}
      - GOOGLE_BUSINESS_CLIENT_SECRET=${GOOGLE_BUSINESS_CLIENT_SECRET}
      - GOOGLE_MEET_CLIENT_ID=${GOOGLE_MEET_CLIENT_ID}
      - GOOGLE_MEET_CLIENT_SECRET=${GOOGLE_MEET_CLIENT_SECRET}
